import {
  Square,
  Leaf,
  Package,
  CircleDot,
  Circle,
  CircleDashed,
  Shapes,
  Sparkles,
  Egg,
  CupSoda,
  SquareDashed,
  Beaker,
  Drumstick,
  Fish,
  Beef,
  Wheat,
  Sandwich,
  Apple,
  Carrot,
  Citrus,
  Nut,
  Droplet,
  Flower,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  square: Square,
  "square-stack": Square,
  leaf: Leaf,
  package: Package,
  "circle-dot": CircleDot,
  circle: Circle,
  "circle-dashed": CircleDashed,
  shapes: Shapes,
  sparkles: Sparkles,
  egg: Egg,
  "cup-soda": CupSoda,
  "square-dashed": SquareDashed,
  beaker: Beaker,
  drumstick: Drumstick,
  fish: Fish,
  beef: Beef,
  wheat: Wheat,
  grain: Wheat,
  sandwich: Sandwich,
  apple: Apple,
  carrot: Carrot,
  citrus: Citrus,
  pepper: Circle,
  nut: Nut,
  droplet: Droplet,
  flower: Flower,
  jar: Package,
  avocado: Leaf,
};

export function getFoodIcon(iconKey: string): LucideIcon {
  return ICONS[iconKey] ?? Leaf;
}
