export const dietaryProfilesSeed = [
  {
    slug: "vegano",
    name: "Vegano",
    shortDesc: "Nenhum produto de origem animal, incluindo derivados.",
    longDesc:
      "Exclui carne, peixe, ovos, laticínios, mel e qualquer derivado animal. Toda a proteína vem de leguminosas, soja, cereais e sementes. Precisa de atenção extra a B12, ferro, zinco, ômega-3 e cálcio.",
    allowsFish: false,
    allowsWhiteMeat: false,
    allowsRedMeat: false,
    allowsDairy: false,
    allowsEggs: false,
    allowsHoney: false,
    sortOrder: 1,
  },
  {
    slug: "vegetariano",
    name: "Vegetariano (ovolactovegetariano)",
    shortDesc: "Sem carne nem peixe, mas come ovos e laticínios.",
    longDesc:
      "Exclui toda carne e peixe, mas mantém ovos e laticínios na dieta — o que facilita atingir a meta de proteína completa e B12 em comparação ao vegano.",
    allowsFish: false,
    allowsWhiteMeat: false,
    allowsRedMeat: false,
    allowsDairy: true,
    allowsEggs: true,
    allowsHoney: true,
    sortOrder: 2,
  },
  {
    slug: "lactovegetariano",
    name: "Lactovegetariano",
    shortDesc: "Sem carne, peixe nem ovos, mas come laticínios.",
    longDesc:
      "Exclui carne, peixe e ovos, mas consome leite, queijo, iogurte e outros laticínios como fonte de proteína animal.",
    allowsFish: false,
    allowsWhiteMeat: false,
    allowsRedMeat: false,
    allowsDairy: true,
    allowsEggs: false,
    allowsHoney: true,
    sortOrder: 3,
  },
  {
    slug: "ovovegetariano",
    name: "Ovovegetariano",
    shortDesc: "Sem carne, peixe nem laticínios, mas come ovos.",
    longDesc:
      "Exclui carne, peixe e laticínios, mas consome ovos como principal fonte de proteína animal completa.",
    allowsFish: false,
    allowsWhiteMeat: false,
    allowsRedMeat: false,
    allowsDairy: false,
    allowsEggs: true,
    allowsHoney: true,
    sortOrder: 4,
  },
  {
    slug: "pescetariano",
    name: "Pescetariano (só peixe como proteína animal)",
    shortDesc: "Come peixe e frutos do mar, mas não carne nem aves.",
    longDesc:
      "Exclui carne vermelha e aves, mas inclui peixe e frutos do mar como principal fonte de proteína animal, além de ovos e laticínios se desejar.",
    allowsFish: true,
    allowsWhiteMeat: false,
    allowsRedMeat: false,
    allowsDairy: true,
    allowsEggs: true,
    allowsHoney: true,
    sortOrder: 5,
  },
  {
    slug: "pollotariano",
    name: "Pollotariano (só aves como proteína)",
    shortDesc: "Come frango e aves, mas não carne vermelha nem peixe.",
    longDesc:
      "Exclui carne vermelha e peixe, mas inclui frango, peru e outras aves como principal fonte de proteína animal.",
    allowsFish: false,
    allowsWhiteMeat: true,
    allowsRedMeat: false,
    allowsDairy: true,
    allowsEggs: true,
    allowsHoney: true,
    sortOrder: 6,
  },
  {
    slug: "carne-vermelha",
    name: "Só carne vermelha como proteína",
    shortDesc: "Carne vermelha como principal proteína, sem aves nem peixe.",
    longDesc:
      "Inclui carne vermelha como principal fonte de proteína animal, sem frango, peru ou peixe. Ovos e laticínios podem ser incluídos.",
    allowsFish: false,
    allowsWhiteMeat: false,
    allowsRedMeat: true,
    allowsDairy: true,
    allowsEggs: true,
    allowsHoney: true,
    sortOrder: 7,
  },
  {
    slug: "flexitariano",
    name: "Flexitariano",
    shortDesc: "Base vegetariana, com carne ocasional.",
    longDesc:
      "Dieta majoritariamente vegetariana, mas sem exclusão rígida — inclui carne, peixe ou aves esporadicamente. Boa transição para quem está reduzindo consumo animal.",
    allowsFish: true,
    allowsWhiteMeat: true,
    allowsRedMeat: true,
    allowsDairy: true,
    allowsEggs: true,
    allowsHoney: true,
    sortOrder: 8,
  },
  {
    slug: "onivoro",
    name: "Onívoro (sem restrições)",
    shortDesc: "Come todos os grupos de proteína animal e vegetal.",
    longDesc:
      "Nenhuma restrição alimentar por escolha ética/dietética — inclui carne vermelha, aves, peixe, ovos e laticínios livremente.",
    allowsFish: true,
    allowsWhiteMeat: true,
    allowsRedMeat: true,
    allowsDairy: true,
    allowsEggs: true,
    allowsHoney: true,
    sortOrder: 9,
  },
  {
    slug: "personalizado",
    name: "Personalizado",
    shortDesc: "Você escolhe exatamente quais proteínas/derivados consome.",
    longDesc:
      "Nenhum dos perfis acima encaixa perfeitamente? Marque manualmente quais grupos (carne vermelha, aves, peixe, ovos, laticínios, mel) você consome e o app monta seu perfil sob medida.",
    allowsFish: true,
    allowsWhiteMeat: true,
    allowsRedMeat: true,
    allowsDairy: true,
    allowsEggs: true,
    allowsHoney: true,
    sortOrder: 10,
  },
];
