export type FoodSeed = {
  slug: string;
  name: string;
  category: "PROTEIN" | "FIBER" | "VITAMIN" | "MINERAL" | "COMPLEX_CARB" | "GOOD_FAT";
  iconKey: string;
  containsAnimalProduct: boolean;
  isMeat: boolean;
  isFish: boolean;
  isDairy: boolean;
  isEgg: boolean;
  kcal100g: number;
  protein100g: number;
  carbs100g: number;
  fat100g: number;
  fiber100g: number;
  sodium100gMg: number;
  sugar100gG: number;
  highlightMicros: string[];
  feasibilityTags: ("BAIXO_CUSTO" | "MEDIO_CUSTO" | "ALTO_CUSTO" | "FACIL_DE_ACHAR" | "ESPECIALIZADO")[];
};

export const foodsSeed: FoodSeed[] = [
  { slug: "tofu-firme", name: "Tofu firme", category: "PROTEIN", iconKey: "square", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 144, protein100g: 15.8, carbs100g: 3, fat100g: 8.7, fiber100g: 2.3, sodium100gMg: 12, sugar100gG: 0.6, highlightMicros: ["Cálcio", "Ferro", "Proteína completa"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "tempeh", name: "Tempeh", category: "PROTEIN", iconKey: "square-stack", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 192, protein100g: 20, carbs100g: 8, fat100g: 11, fiber100g: 9, sodium100gMg: 9, sugar100gG: 0, highlightMicros: ["Probióticos", "Ferro", "Proteína completa"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "edamame", name: "Edamame (soja verde)", category: "PROTEIN", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 121, protein100g: 12, carbs100g: 10, fat100g: 5, fiber100g: 5, sodium100gMg: 6, sugar100gG: 2.2, highlightMicros: ["Folato", "Vitamina K"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "proteina-soja-texturizada", name: "Proteína de soja texturizada (PTS)", category: "PROTEIN", iconKey: "package", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 100, protein100g: 18, carbs100g: 8, fat100g: 1, fiber100g: 4, sodium100gMg: 3, sugar100gG: 1, highlightMicros: ["Ferro", "Baixo custo por grama de proteína"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "lentilha-cozida", name: "Lentilha cozida", category: "PROTEIN", iconKey: "circle-dot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 116, protein100g: 9, carbs100g: 20, fat100g: 0.4, fiber100g: 8, sodium100gMg: 2, sugar100gG: 1.8, highlightMicros: ["Ferro", "Folato"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "grao-de-bico-cozido", name: "Grão-de-bico cozido", category: "PROTEIN", iconKey: "circle", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 164, protein100g: 9, carbs100g: 27, fat100g: 2.6, fiber100g: 8, sodium100gMg: 7, sugar100gG: 4.8, highlightMicros: ["Ferro", "Manganês"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "feijao-preto-cozido", name: "Feijão preto cozido", category: "PROTEIN", iconKey: "circle-dashed", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 132, protein100g: 8.9, carbs100g: 24, fat100g: 0.5, fiber100g: 8.7, sodium100gMg: 2, sugar100gG: 0.3, highlightMicros: ["Ferro", "Magnésio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "seitan", name: "Seitan (glúten de trigo)", category: "PROTEIN", iconKey: "shapes", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 120, protein100g: 21, carbs100g: 4, fat100g: 2, fiber100g: 1, sodium100gMg: 15, sugar100gG: 0, highlightMicros: ["Alta densidade proteica"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "spirulina", name: "Spirulina (seca)", category: "PROTEIN", iconKey: "sparkles", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 290, protein100g: 57, carbs100g: 24, fat100g: 8, fiber100g: 3.6, sodium100gMg: 1048, sugar100gG: 3.1, highlightMicros: ["Ferro", "Proteína completa"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "ovo-inteiro", name: "Ovo de galinha inteiro", category: "PROTEIN", iconKey: "egg", containsAnimalProduct: true, isMeat: false, isFish: false, isDairy: false, isEgg: true, kcal100g: 143, protein100g: 13, carbs100g: 1.1, fat100g: 9.5, fiber100g: 0, sodium100gMg: 142, sugar100gG: 1.1, highlightMicros: ["Colina", "Vitamina B12"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "iogurte-grego-natural", name: "Iogurte grego natural", category: "PROTEIN", iconKey: "cup-soda", containsAnimalProduct: true, isMeat: false, isFish: false, isDairy: true, isEgg: false, kcal100g: 59, protein100g: 10, carbs100g: 3.6, fat100g: 0.4, fiber100g: 0, sodium100gMg: 36, sugar100gG: 3.2, highlightMicros: ["Cálcio", "Probióticos"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "queijo-cottage", name: "Queijo cottage", category: "PROTEIN", iconKey: "square-dashed", containsAnimalProduct: true, isMeat: false, isFish: false, isDairy: true, isEgg: false, kcal100g: 98, protein100g: 11, carbs100g: 3.4, fat100g: 4.3, fiber100g: 0, sodium100gMg: 364, sugar100gG: 2.7, highlightMicros: ["Cálcio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "whey-protein", name: "Whey protein (pó)", category: "PROTEIN", iconKey: "beaker", containsAnimalProduct: true, isMeat: false, isFish: false, isDairy: true, isEgg: false, kcal100g: 400, protein100g: 80, carbs100g: 8, fat100g: 6, fiber100g: 1, sodium100gMg: 150, sugar100gG: 4, highlightMicros: ["Leucina", "Absorção rápida"], feasibilityTags: ["ALTO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "frango-peito-grelhado", name: "Peito de frango grelhado", category: "PROTEIN", iconKey: "drumstick", containsAnimalProduct: true, isMeat: true, isFish: false, isDairy: false, isEgg: false, kcal100g: 165, protein100g: 31, carbs100g: 0, fat100g: 3.6, fiber100g: 0, sodium100gMg: 74, sugar100gG: 0, highlightMicros: ["Vitamina B6"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "peru-moido", name: "Peru moído (93% magro)", category: "PROTEIN", iconKey: "drumstick", containsAnimalProduct: true, isMeat: true, isFish: false, isDairy: false, isEgg: false, kcal100g: 208, protein100g: 26, carbs100g: 0, fat100g: 11, fiber100g: 0, sodium100gMg: 107, sugar100gG: 0, highlightMicros: ["Zinco", "Vitamina B6"], feasibilityTags: ["MEDIO_CUSTO"] },
  { slug: "tilapia", name: "Tilápia grelhada", category: "PROTEIN", iconKey: "fish", containsAnimalProduct: true, isMeat: false, isFish: true, isDairy: false, isEgg: false, kcal100g: 128, protein100g: 26, carbs100g: 0, fat100g: 2.7, fiber100g: 0, sodium100gMg: 56, sugar100gG: 0, highlightMicros: ["Selênio", "Vitamina B12"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "salmao", name: "Salmão grelhado", category: "PROTEIN", iconKey: "fish", containsAnimalProduct: true, isMeat: false, isFish: true, isDairy: false, isEgg: false, kcal100g: 208, protein100g: 20, carbs100g: 0, fat100g: 13, fiber100g: 0, sodium100gMg: 59, sugar100gG: 0, highlightMicros: ["Ômega-3", "Vitamina D"], feasibilityTags: ["ALTO_CUSTO"] },
  { slug: "atum-enlatado", name: "Atum enlatado (em água)", category: "PROTEIN", iconKey: "fish", containsAnimalProduct: true, isMeat: false, isFish: true, isDairy: false, isEgg: false, kcal100g: 132, protein100g: 28, carbs100g: 0, fat100g: 1, fiber100g: 0, sodium100gMg: 320, sugar100gG: 0, highlightMicros: ["Selênio", "Vitamina D"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "carne-bovina-magra", name: "Carne bovina magra (patinho)", category: "PROTEIN", iconKey: "beef", containsAnimalProduct: true, isMeat: true, isFish: false, isDairy: false, isEgg: false, kcal100g: 172, protein100g: 20, carbs100g: 0, fat100g: 10, fiber100g: 0, sodium100gMg: 60, sugar100gG: 0, highlightMicros: ["Ferro heme", "Vitamina B12", "Zinco"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "arroz-integral-cozido", name: "Arroz integral cozido", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 123, protein100g: 2.7, carbs100g: 26, fat100g: 1, fiber100g: 1.8, sodium100gMg: 4, sugar100gG: 0.4, highlightMicros: ["Magnésio", "Selênio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "batata-doce-cozida", name: "Batata-doce cozida", category: "COMPLEX_CARB", iconKey: "leafy-green", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 86, protein100g: 1.6, carbs100g: 20, fat100g: 0.1, fiber100g: 3, sodium100gMg: 55, sugar100gG: 4.2, highlightMicros: ["Vitamina A (betacaroteno)"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "aveia-flocos", name: "Aveia em flocos", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 389, protein100g: 17, carbs100g: 66, fat100g: 7, fiber100g: 10, sodium100gMg: 2, sugar100gG: 0.99, highlightMicros: ["Beta-glucana", "Manganês"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "quinoa-cozida", name: "Quinoa cozida", category: "COMPLEX_CARB", iconKey: "grain", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 120, protein100g: 4.4, carbs100g: 21, fat100g: 1.9, fiber100g: 2.8, sodium100gMg: 7, sugar100gG: 0.9, highlightMicros: ["Proteína completa", "Magnésio"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "pao-integral", name: "Pão integral", category: "COMPLEX_CARB", iconKey: "sandwich", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 247, protein100g: 9, carbs100g: 41, fat100g: 3.4, fiber100g: 7, sodium100gMg: 400, sugar100gG: 5, highlightMicros: ["Fibra"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "macarrao-integral-cozido", name: "Macarrão integral cozido", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 124, protein100g: 5, carbs100g: 25, fat100g: 1.1, fiber100g: 3.2, sodium100gMg: 4, sugar100gG: 0.8, highlightMicros: ["Fibra"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "milho-cozido", name: "Milho cozido", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 96, protein100g: 3.4, carbs100g: 21, fat100g: 1.5, fiber100g: 2.4, sodium100gMg: 15, sugar100gG: 4.5, highlightMicros: ["Luteína"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "arroz-selvagem-cozido", name: "Arroz selvagem cozido", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 101, protein100g: 4, carbs100g: 21, fat100g: 0.3, fiber100g: 1.8, sodium100gMg: 3, sugar100gG: 0.7, highlightMicros: ["Manganês", "Antioxidantes"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "cevadinha-cozida", name: "Cevadinha cozida", category: "COMPLEX_CARB", iconKey: "grain", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 123, protein100g: 2.3, carbs100g: 28, fat100g: 0.4, fiber100g: 3.8, sodium100gMg: 3, sugar100gG: 0.4, highlightMicros: ["Betaglucana"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "trigo-sarraceno-cozido", name: "Trigo sarraceno cozido", category: "COMPLEX_CARB", iconKey: "grain", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 92, protein100g: 3.4, carbs100g: 20, fat100g: 0.6, fiber100g: 2.7, sodium100gMg: 1, sugar100gG: 0.9, highlightMicros: ["Rutina", "Magnésio"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "inhame-cozido", name: "Inhame cozido", category: "COMPLEX_CARB", iconKey: "carrot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 118, protein100g: 1.5, carbs100g: 28, fat100g: 0.2, fiber100g: 4.1, sodium100gMg: 9, sugar100gG: 0.5, highlightMicros: ["Potássio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "mandioca-cozida", name: "Mandioca (aipim) cozida", category: "COMPLEX_CARB", iconKey: "carrot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 125, protein100g: 0.6, carbs100g: 30, fat100g: 0.2, fiber100g: 1.5, sodium100gMg: 10, sugar100gG: 1.4, highlightMicros: ["Vitamina C"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "batata-inglesa-cozida", name: "Batata inglesa cozida (com casca)", category: "COMPLEX_CARB", iconKey: "circle", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 87, protein100g: 1.9, carbs100g: 20, fat100g: 0.1, fiber100g: 1.8, sodium100gMg: 6, sugar100gG: 0.9, highlightMicros: ["Potássio", "Vitamina C"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "cuscuz-marroquino-cozido", name: "Cuscuz marroquino cozido", category: "COMPLEX_CARB", iconKey: "grain", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 112, protein100g: 3.8, carbs100g: 23, fat100g: 0.2, fiber100g: 1.4, sodium100gMg: 5, sugar100gG: 0.1, highlightMicros: ["Selênio"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "painco-cozido", name: "Painço cozido", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 119, protein100g: 3.5, carbs100g: 24, fat100g: 1, fiber100g: 1.3, sodium100gMg: 2, sugar100gG: 0.2, highlightMicros: ["Magnésio"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "banana-da-terra-cozida", name: "Banana-da-terra cozida", category: "COMPLEX_CARB", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 122, protein100g: 1.3, carbs100g: 32, fat100g: 0.3, fiber100g: 2.3, sodium100gMg: 4, sugar100gG: 15, highlightMicros: ["Vitamina A"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "pao-de-centeio", name: "Pão de centeio", category: "COMPLEX_CARB", iconKey: "sandwich", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 259, protein100g: 8.5, carbs100g: 48, fat100g: 3.3, fiber100g: 5.8, sodium100gMg: 660, sugar100gG: 3.9, highlightMicros: ["Fibra"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "tapioca-goma", name: "Tapioca (goma hidratada)", category: "COMPLEX_CARB", iconKey: "circle", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 240, protein100g: 0.2, carbs100g: 59, fat100g: 0, fiber100g: 0.5, sodium100gMg: 1, sugar100gG: 3, highlightMicros: ["Sem glúten"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "polenta-cozida", name: "Polenta cozida", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 85, protein100g: 2, carbs100g: 18, fat100g: 0.5, fiber100g: 1.1, sodium100gMg: 250, sugar100gG: 0.3, highlightMicros: ["Sem glúten"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "macarrao-de-arroz-cozido", name: "Macarrão de arroz cozido", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 109, protein100g: 1.8, carbs100g: 25, fat100g: 0.2, fiber100g: 1, sodium100gMg: 3, sugar100gG: 0.1, highlightMicros: ["Sem glúten"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "brocolis-cozido", name: "Brócolis cozido", category: "FIBER", iconKey: "leafy-green", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 35, protein100g: 2.4, carbs100g: 7, fat100g: 0.4, fiber100g: 3.3, sodium100gMg: 41, sugar100gG: 1.4, highlightMicros: ["Vitamina C", "Vitamina K"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "couve-crua", name: "Couve crua", category: "FIBER", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 49, protein100g: 4.3, carbs100g: 9, fat100g: 0.9, fiber100g: 3.6, sodium100gMg: 38, sugar100gG: 2.3, highlightMicros: ["Vitamina K", "Vitamina A"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "chia", name: "Semente de chia", category: "FIBER", iconKey: "circle-dot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 486, protein100g: 17, carbs100g: 42, fat100g: 31, fiber100g: 34, sodium100gMg: 16, sugar100gG: 0, highlightMicros: ["Ômega-3 (ALA)", "Cálcio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "feijao-branco-cozido", name: "Feijão branco cozido", category: "FIBER", iconKey: "circle-dashed", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 139, protein100g: 9.7, carbs100g: 25, fat100g: 0.5, fiber100g: 6.3, sodium100gMg: 5, sugar100gG: 0.3, highlightMicros: ["Ferro", "Potássio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "maca-com-casca", name: "Maçã com casca", category: "FIBER", iconKey: "apple", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 52, protein100g: 0.3, carbs100g: 14, fat100g: 0.2, fiber100g: 2.4, sodium100gMg: 1, sugar100gG: 10, highlightMicros: ["Vitamina C", "Pectina"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "couve-flor-cozida", name: "Couve-flor cozida", category: "FIBER", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 23, protein100g: 1.8, carbs100g: 4.1, fat100g: 0.3, fiber100g: 2.3, sodium100gMg: 15, sugar100gG: 2, highlightMicros: ["Vitamina C"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "abobrinha-refogada", name: "Abobrinha refogada", category: "FIBER", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 20, protein100g: 1.4, carbs100g: 3.4, fat100g: 0.4, fiber100g: 1.5, sodium100gMg: 3, sugar100gG: 2.2, highlightMicros: ["Potássio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "berinjela-assada", name: "Berinjela assada", category: "FIBER", iconKey: "circle-dot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 35, protein100g: 0.8, carbs100g: 8.6, fat100g: 0.2, fiber100g: 3, sodium100gMg: 1, sugar100gG: 3.2, highlightMicros: ["Antioxidantes"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "ervilha-cozida", name: "Ervilha cozida", category: "FIBER", iconKey: "circle-dot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 84, protein100g: 5.4, carbs100g: 14, fat100g: 0.4, fiber100g: 5.5, sodium100gMg: 3, sugar100gG: 5.7, highlightMicros: ["Vitamina K", "Folato"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "vagem-cozida", name: "Vagem cozida", category: "FIBER", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 35, protein100g: 1.8, carbs100g: 7.9, fat100g: 0.2, fiber100g: 3.2, sodium100gMg: 6, sugar100gG: 3.6, highlightMicros: ["Vitamina C"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "repolho-cru", name: "Repolho cru", category: "FIBER", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 25, protein100g: 1.3, carbs100g: 5.8, fat100g: 0.1, fiber100g: 2.5, sodium100gMg: 18, sugar100gG: 3.2, highlightMicros: ["Vitamina K", "Vitamina C"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "quiabo-cozido", name: "Quiabo cozido", category: "FIBER", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 33, protein100g: 1.9, carbs100g: 7.5, fat100g: 0.2, fiber100g: 3.2, sodium100gMg: 8, sugar100gG: 1.5, highlightMicros: ["Vitamina K"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "abobora-cozida", name: "Abóbora cozida", category: "FIBER", iconKey: "carrot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 39, protein100g: 1.1, carbs100g: 9, fat100g: 0.3, fiber100g: 2.5, sodium100gMg: 1, sugar100gG: 2.8, highlightMicros: ["Vitamina A"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "pera-com-casca", name: "Pera com casca", category: "FIBER", iconKey: "apple", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 57, protein100g: 0.4, carbs100g: 15, fat100g: 0.1, fiber100g: 3.1, sodium100gMg: 1, sugar100gG: 10, highlightMicros: ["Vitamina C"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "framboesa", name: "Framboesa", category: "FIBER", iconKey: "sparkles", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 52, protein100g: 1.2, carbs100g: 12, fat100g: 0.7, fiber100g: 6.5, sodium100gMg: 1, sugar100gG: 4.4, highlightMicros: ["Antioxidantes", "Vitamina C"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "goiaba", name: "Goiaba", category: "FIBER", iconKey: "citrus", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 68, protein100g: 2.6, carbs100g: 14, fat100g: 1, fiber100g: 5.4, sodium100gMg: 2, sugar100gG: 8.9, highlightMicros: ["Vitamina C"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "linhaca-triturada", name: "Linhaça triturada", category: "FIBER", iconKey: "circle-dot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 534, protein100g: 18, carbs100g: 29, fat100g: 42, fiber100g: 27, sodium100gMg: 30, sugar100gG: 1.6, highlightMicros: ["Ômega-3 (ALA)", "Lignanas"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "farelo-de-aveia", name: "Farelo de aveia", category: "FIBER", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 246, protein100g: 17, carbs100g: 66, fat100g: 7, fiber100g: 15, sodium100gMg: 4, sugar100gG: 0, highlightMicros: ["Beta-glucana"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "feijao-carioca-cozido", name: "Feijão carioca cozido", category: "FIBER", iconKey: "circle-dashed", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 76, protein100g: 4.8, carbs100g: 13.6, fat100g: 0.5, fiber100g: 8.5, sodium100gMg: 2, sugar100gG: 0.3, highlightMicros: ["Ferro", "Folato"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "ameixa-seca", name: "Ameixa seca", category: "FIBER", iconKey: "circle", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 240, protein100g: 2.2, carbs100g: 64, fat100g: 0.4, fiber100g: 7.1, sodium100gMg: 2, sugar100gG: 38, highlightMicros: ["Potássio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "espinafre-cru", name: "Espinafre cru", category: "VITAMIN", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 23, protein100g: 2.9, carbs100g: 3.6, fat100g: 0.4, fiber100g: 2.2, sodium100gMg: 79, sugar100gG: 0.4, highlightMicros: ["Vitamina K", "Vitamina A", "Folato", "Ferro"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "cenoura-crua", name: "Cenoura crua", category: "VITAMIN", iconKey: "carrot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 41, protein100g: 0.9, carbs100g: 10, fat100g: 0.2, fiber100g: 2.8, sodium100gMg: 69, sugar100gG: 4.7, highlightMicros: ["Vitamina A (betacaroteno)"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "laranja", name: "Laranja", category: "VITAMIN", iconKey: "citrus", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 47, protein100g: 0.9, carbs100g: 12, fat100g: 0.1, fiber100g: 2.4, sodium100gMg: 0, sugar100gG: 9.4, highlightMicros: ["Vitamina C"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "pimentao-vermelho", name: "Pimentão vermelho", category: "VITAMIN", iconKey: "pepper", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 31, protein100g: 1, carbs100g: 6, fat100g: 0.3, fiber100g: 2.1, sodium100gMg: 4, sugar100gG: 4.2, highlightMicros: ["Vitamina C", "Vitamina A"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "sementes-abobora", name: "Sementes de abóbora", category: "MINERAL", iconKey: "circle-dot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 559, protein100g: 30, carbs100g: 11, fat100g: 49, fiber100g: 6, sodium100gMg: 7, sugar100gG: 1.4, highlightMicros: ["Zinco", "Magnésio", "Ferro"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "amendoas", name: "Amêndoas", category: "MINERAL", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 579, protein100g: 21, carbs100g: 22, fat100g: 50, fiber100g: 12.5, sodium100gMg: 1, sugar100gG: 4.4, highlightMicros: ["Magnésio", "Vitamina E", "Cálcio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "melado-cana", name: "Melado de cana", category: "MINERAL", iconKey: "droplet", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 290, protein100g: 0, carbs100g: 75, fat100g: 0, fiber100g: 0, sodium100gMg: 37, sugar100gG: 60, highlightMicros: ["Ferro", "Cálcio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "abacate", name: "Abacate", category: "GOOD_FAT", iconKey: "avocado", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 160, protein100g: 2, carbs100g: 8.5, fat100g: 14.7, fiber100g: 6.7, sodium100gMg: 7, sugar100gG: 0.7, highlightMicros: ["Gordura monoinsaturada", "Potássio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "azeite-oliva", name: "Azeite de oliva extra virgem", category: "GOOD_FAT", iconKey: "droplet", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 884, protein100g: 0, carbs100g: 0, fat100g: 100, fiber100g: 0, sodium100gMg: 2, sugar100gG: 0, highlightMicros: ["Gordura monoinsaturada", "Antioxidantes"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "castanha-para", name: "Castanha-do-pará", category: "GOOD_FAT", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 656, protein100g: 14, carbs100g: 12, fat100g: 66, fiber100g: 7.5, sodium100gMg: 3, sugar100gG: 2.3, highlightMicros: ["Selênio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "nozes", name: "Nozes", category: "GOOD_FAT", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 654, protein100g: 15, carbs100g: 14, fat100g: 65, fiber100g: 6.7, sodium100gMg: 2, sugar100gG: 2.6, highlightMicros: ["Ômega-3 (ALA)"], feasibilityTags: ["ALTO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "pasta-amendoim", name: "Pasta de amendoim integral", category: "GOOD_FAT", iconKey: "jar", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 588, protein100g: 25, carbs100g: 20, fat100g: 50, fiber100g: 6, sodium100gMg: 17, sugar100gG: 4, highlightMicros: ["Niacina"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "sementes-girassol", name: "Sementes de girassol", category: "GOOD_FAT", iconKey: "flower", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 584, protein100g: 21, carbs100g: 20, fat100g: 51, fiber100g: 8.6, sodium100gMg: 9, sugar100gG: 2.6, highlightMicros: ["Vitamina E", "Selênio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "oleo-de-coco", name: "Óleo de coco", category: "GOOD_FAT", iconKey: "droplet", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 862, protein100g: 0, carbs100g: 0, fat100g: 100, fiber100g: 0, sodium100gMg: 0, sugar100gG: 0, highlightMicros: ["Triglicerídeos de cadeia média"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "amendoim-torrado", name: "Amendoim torrado", category: "GOOD_FAT", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 567, protein100g: 26, carbs100g: 16, fat100g: 49, fiber100g: 8, sodium100gMg: 18, sugar100gG: 4, highlightMicros: ["Niacina", "Magnésio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "castanha-de-caju", name: "Castanha de caju", category: "GOOD_FAT", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 553, protein100g: 18, carbs100g: 30, fat100g: 44, fiber100g: 3.3, sodium100gMg: 12, sugar100gG: 5.9, highlightMicros: ["Cobre", "Magnésio"], feasibilityTags: ["ALTO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "pistache", name: "Pistache", category: "GOOD_FAT", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 560, protein100g: 20, carbs100g: 28, fat100g: 45, fiber100g: 10, sodium100gMg: 1, sugar100gG: 7.7, highlightMicros: ["Vitamina B6", "Luteína"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "macadamia", name: "Macadâmia", category: "GOOD_FAT", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 718, protein100g: 8, carbs100g: 14, fat100g: 76, fiber100g: 8.6, sodium100gMg: 5, sugar100gG: 4.6, highlightMicros: ["Gordura monoinsaturada"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "oleo-de-linhaca", name: "Óleo de linhaça", category: "GOOD_FAT", iconKey: "droplet", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 884, protein100g: 0, carbs100g: 0, fat100g: 100, fiber100g: 0, sodium100gMg: 0, sugar100gG: 0, highlightMicros: ["Ômega-3 (ALA)"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "tahine", name: "Tahine (pasta de gergelim)", category: "GOOD_FAT", iconKey: "jar", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 595, protein100g: 17, carbs100g: 21, fat100g: 54, fiber100g: 9.3, sodium100gMg: 115, sugar100gG: 0.5, highlightMicros: ["Cálcio", "Ferro"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "azeitona-preta", name: "Azeitona preta", category: "GOOD_FAT", iconKey: "circle", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 115, protein100g: 0.8, carbs100g: 6, fat100g: 11, fiber100g: 3.2, sodium100gMg: 735, sugar100gG: 0, highlightMicros: ["Gordura monoinsaturada"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "leite-de-coco", name: "Leite de coco", category: "GOOD_FAT", iconKey: "cup-soda", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 230, protein100g: 2.3, carbs100g: 5.5, fat100g: 24, fiber100g: 2.2, sodium100gMg: 15, sugar100gG: 3.3, highlightMicros: ["Manganês"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "manteiga-de-amendoa", name: "Manteiga de amêndoa", category: "GOOD_FAT", iconKey: "jar", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 614, protein100g: 21, carbs100g: 19, fat100g: 56, fiber100g: 10.3, sodium100gMg: 7, sugar100gG: 4.3, highlightMicros: ["Vitamina E", "Cálcio"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "oleo-de-gergelim", name: "Óleo de gergelim", category: "GOOD_FAT", iconKey: "droplet", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 884, protein100g: 0, carbs100g: 0, fat100g: 100, fiber100g: 0, sodium100gMg: 0, sugar100gG: 0, highlightMicros: ["Antioxidantes (sesamol)"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "creme-de-castanha-de-caju", name: "Creme de castanha de caju", category: "GOOD_FAT", iconKey: "jar", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 350, protein100g: 9, carbs100g: 15, fat100g: 28, fiber100g: 1.5, sodium100gMg: 5, sugar100gG: 3, highlightMicros: ["Magnésio"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "oleo-de-abacate", name: "Óleo de abacate", category: "GOOD_FAT", iconKey: "droplet", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 884, protein100g: 0, carbs100g: 0, fat100g: 100, fiber100g: 0, sodium100gMg: 0, sugar100gG: 0, highlightMicros: ["Gordura monoinsaturada"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "coco-ralado", name: "Coco ralado (sem açúcar)", category: "GOOD_FAT", iconKey: "sparkles", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 660, protein100g: 6.9, carbs100g: 24, fat100g: 65, fiber100g: 16, sodium100gMg: 37, sugar100gG: 7, highlightMicros: ["Manganês", "Cobre"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
];
