export type FoodSeed = {
  slug: string;
  name: string;
  category: "PROTEIN" | "FIBER" | "VITAMIN" | "MINERAL" | "COMPLEX_CARB" | "GOOD_FAT";
  iconKey: string;
  containsAnimalProduct: boolean;
  isMeat: boolean;
  isFish: boolean;
  isDairy: boolean;
  isEgg: boolean;
  kcal100g: number;
  protein100g: number;
  carbs100g: number;
  fat100g: number;
  fiber100g: number;
  sodium100gMg: number;
  sugar100gG: number;
  highlightMicros: string[];
  feasibilityTags: ("BAIXO_CUSTO" | "MEDIO_CUSTO" | "ALTO_CUSTO" | "FACIL_DE_ACHAR" | "ESPECIALIZADO")[];
};

export const foodsSeed: FoodSeed[] = [
  { slug: "tofu-firme", name: "Tofu firme", category: "PROTEIN", iconKey: "square", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 144, protein100g: 15.8, carbs100g: 3, fat100g: 8.7, fiber100g: 2.3, sodium100gMg: 12, sugar100gG: 0.6, highlightMicros: ["Cálcio", "Ferro", "Proteína completa"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "tempeh", name: "Tempeh", category: "PROTEIN", iconKey: "square-stack", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 192, protein100g: 20, carbs100g: 8, fat100g: 11, fiber100g: 9, sodium100gMg: 9, sugar100gG: 0, highlightMicros: ["Probióticos", "Ferro", "Proteína completa"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "edamame", name: "Edamame (soja verde)", category: "PROTEIN", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 121, protein100g: 12, carbs100g: 10, fat100g: 5, fiber100g: 5, sodium100gMg: 6, sugar100gG: 2.2, highlightMicros: ["Folato", "Vitamina K"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "proteina-soja-texturizada", name: "Proteína de soja texturizada (PTS)", category: "PROTEIN", iconKey: "package", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 100, protein100g: 18, carbs100g: 8, fat100g: 1, fiber100g: 4, sodium100gMg: 3, sugar100gG: 1, highlightMicros: ["Ferro", "Baixo custo por grama de proteína"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "lentilha-cozida", name: "Lentilha cozida", category: "PROTEIN", iconKey: "circle-dot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 116, protein100g: 9, carbs100g: 20, fat100g: 0.4, fiber100g: 8, sodium100gMg: 2, sugar100gG: 1.8, highlightMicros: ["Ferro", "Folato"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "grao-de-bico-cozido", name: "Grão-de-bico cozido", category: "PROTEIN", iconKey: "circle", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 164, protein100g: 9, carbs100g: 27, fat100g: 2.6, fiber100g: 8, sodium100gMg: 7, sugar100gG: 4.8, highlightMicros: ["Ferro", "Manganês"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "feijao-preto-cozido", name: "Feijão preto cozido", category: "PROTEIN", iconKey: "circle-dashed", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 132, protein100g: 8.9, carbs100g: 24, fat100g: 0.5, fiber100g: 8.7, sodium100gMg: 2, sugar100gG: 0.3, highlightMicros: ["Ferro", "Magnésio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "seitan", name: "Seitan (glúten de trigo)", category: "PROTEIN", iconKey: "shapes", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 120, protein100g: 21, carbs100g: 4, fat100g: 2, fiber100g: 1, sodium100gMg: 15, sugar100gG: 0, highlightMicros: ["Alta densidade proteica"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "spirulina", name: "Spirulina (seca)", category: "PROTEIN", iconKey: "sparkles", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 290, protein100g: 57, carbs100g: 24, fat100g: 8, fiber100g: 3.6, sodium100gMg: 1048, sugar100gG: 3.1, highlightMicros: ["Ferro", "Proteína completa"], feasibilityTags: ["ALTO_CUSTO", "ESPECIALIZADO"] },
  { slug: "ovo-inteiro", name: "Ovo de galinha inteiro", category: "PROTEIN", iconKey: "egg", containsAnimalProduct: true, isMeat: false, isFish: false, isDairy: false, isEgg: true, kcal100g: 143, protein100g: 13, carbs100g: 1.1, fat100g: 9.5, fiber100g: 0, sodium100gMg: 142, sugar100gG: 1.1, highlightMicros: ["Colina", "Vitamina B12"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "iogurte-grego-natural", name: "Iogurte grego natural", category: "PROTEIN", iconKey: "cup-soda", containsAnimalProduct: true, isMeat: false, isFish: false, isDairy: true, isEgg: false, kcal100g: 59, protein100g: 10, carbs100g: 3.6, fat100g: 0.4, fiber100g: 0, sodium100gMg: 36, sugar100gG: 3.2, highlightMicros: ["Cálcio", "Probióticos"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "queijo-cottage", name: "Queijo cottage", category: "PROTEIN", iconKey: "square-dashed", containsAnimalProduct: true, isMeat: false, isFish: false, isDairy: true, isEgg: false, kcal100g: 98, protein100g: 11, carbs100g: 3.4, fat100g: 4.3, fiber100g: 0, sodium100gMg: 364, sugar100gG: 2.7, highlightMicros: ["Cálcio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "whey-protein", name: "Whey protein (pó)", category: "PROTEIN", iconKey: "beaker", containsAnimalProduct: true, isMeat: false, isFish: false, isDairy: true, isEgg: false, kcal100g: 400, protein100g: 80, carbs100g: 8, fat100g: 6, fiber100g: 1, sodium100gMg: 150, sugar100gG: 4, highlightMicros: ["Leucina", "Absorção rápida"], feasibilityTags: ["ALTO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "frango-peito-grelhado", name: "Peito de frango grelhado", category: "PROTEIN", iconKey: "drumstick", containsAnimalProduct: true, isMeat: true, isFish: false, isDairy: false, isEgg: false, kcal100g: 165, protein100g: 31, carbs100g: 0, fat100g: 3.6, fiber100g: 0, sodium100gMg: 74, sugar100gG: 0, highlightMicros: ["Vitamina B6"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "peru-moido", name: "Peru moído", category: "PROTEIN", iconKey: "drumstick", containsAnimalProduct: true, isMeat: true, isFish: false, isDairy: false, isEgg: false, kcal100g: 170, protein100g: 20, carbs100g: 0, fat100g: 10, fiber100g: 0, sodium100gMg: 70, sugar100gG: 0, highlightMicros: ["Zinco"], feasibilityTags: ["MEDIO_CUSTO"] },
  { slug: "tilapia", name: "Tilápia grelhada", category: "PROTEIN", iconKey: "fish", containsAnimalProduct: true, isMeat: false, isFish: true, isDairy: false, isEgg: false, kcal100g: 96, protein100g: 20, carbs100g: 0, fat100g: 1.7, fiber100g: 0, sodium100gMg: 52, sugar100gG: 0, highlightMicros: ["Selênio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "salmao", name: "Salmão grelhado", category: "PROTEIN", iconKey: "fish", containsAnimalProduct: true, isMeat: false, isFish: true, isDairy: false, isEgg: false, kcal100g: 208, protein100g: 20, carbs100g: 0, fat100g: 13, fiber100g: 0, sodium100gMg: 59, sugar100gG: 0, highlightMicros: ["Ômega-3", "Vitamina D"], feasibilityTags: ["ALTO_CUSTO"] },
  { slug: "atum-enlatado", name: "Atum enlatado (em água)", category: "PROTEIN", iconKey: "fish", containsAnimalProduct: true, isMeat: false, isFish: true, isDairy: false, isEgg: false, kcal100g: 132, protein100g: 28, carbs100g: 0, fat100g: 1, fiber100g: 0, sodium100gMg: 320, sugar100gG: 0, highlightMicros: ["Selênio", "Vitamina D"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "carne-bovina-magra", name: "Carne bovina magra (patinho)", category: "PROTEIN", iconKey: "beef", containsAnimalProduct: true, isMeat: true, isFish: false, isDairy: false, isEgg: false, kcal100g: 172, protein100g: 20, carbs100g: 0, fat100g: 10, fiber100g: 0, sodium100gMg: 60, sugar100gG: 0, highlightMicros: ["Ferro heme", "Vitamina B12", "Zinco"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "arroz-integral-cozido", name: "Arroz integral cozido", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 123, protein100g: 2.7, carbs100g: 26, fat100g: 1, fiber100g: 1.8, sodium100gMg: 4, sugar100gG: 0.4, highlightMicros: ["Magnésio", "Selênio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "batata-doce-cozida", name: "Batata-doce cozida", category: "COMPLEX_CARB", iconKey: "leafy-green", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 86, protein100g: 1.6, carbs100g: 20, fat100g: 0.1, fiber100g: 3, sodium100gMg: 55, sugar100gG: 4.2, highlightMicros: ["Vitamina A (betacaroteno)"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "aveia-flocos", name: "Aveia em flocos", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 389, protein100g: 17, carbs100g: 66, fat100g: 7, fiber100g: 10, sodium100gMg: 2, sugar100gG: 0.99, highlightMicros: ["Beta-glucana", "Manganês"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "quinoa-cozida", name: "Quinoa cozida", category: "COMPLEX_CARB", iconKey: "grain", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 120, protein100g: 4.4, carbs100g: 21, fat100g: 1.9, fiber100g: 2.8, sodium100gMg: 7, sugar100gG: 0.9, highlightMicros: ["Proteína completa", "Magnésio"], feasibilityTags: ["MEDIO_CUSTO", "ESPECIALIZADO"] },
  { slug: "pao-integral", name: "Pão integral", category: "COMPLEX_CARB", iconKey: "sandwich", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 247, protein100g: 9, carbs100g: 41, fat100g: 3.4, fiber100g: 7, sodium100gMg: 400, sugar100gG: 5, highlightMicros: ["Fibra"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "macarrao-integral-cozido", name: "Macarrão integral cozido", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 124, protein100g: 5, carbs100g: 25, fat100g: 1.1, fiber100g: 3.2, sodium100gMg: 4, sugar100gG: 0.8, highlightMicros: ["Fibra"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "milho-cozido", name: "Milho cozido", category: "COMPLEX_CARB", iconKey: "wheat", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 96, protein100g: 3.4, carbs100g: 21, fat100g: 1.5, fiber100g: 2.4, sodium100gMg: 15, sugar100gG: 4.5, highlightMicros: ["Luteína"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "brocolis-cozido", name: "Brócolis cozido", category: "FIBER", iconKey: "leafy-green", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 35, protein100g: 2.4, carbs100g: 7, fat100g: 0.4, fiber100g: 3.3, sodium100gMg: 41, sugar100gG: 1.4, highlightMicros: ["Vitamina C", "Vitamina K"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "couve-crua", name: "Couve crua", category: "FIBER", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 49, protein100g: 4.3, carbs100g: 9, fat100g: 0.9, fiber100g: 3.6, sodium100gMg: 38, sugar100gG: 2.3, highlightMicros: ["Vitamina K", "Vitamina A"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "chia", name: "Semente de chia", category: "FIBER", iconKey: "circle-dot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 486, protein100g: 17, carbs100g: 42, fat100g: 31, fiber100g: 34, sodium100gMg: 16, sugar100gG: 0, highlightMicros: ["Ômega-3 (ALA)", "Cálcio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "feijao-branco-cozido", name: "Feijão branco cozido", category: "FIBER", iconKey: "circle-dashed", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 139, protein100g: 9.7, carbs100g: 25, fat100g: 0.5, fiber100g: 6.3, sodium100gMg: 5, sugar100gG: 0.3, highlightMicros: ["Ferro", "Potássio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "maca-com-casca", name: "Maçã com casca", category: "FIBER", iconKey: "apple", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 52, protein100g: 0.3, carbs100g: 14, fat100g: 0.2, fiber100g: 2.4, sodium100gMg: 1, sugar100gG: 10, highlightMicros: ["Vitamina C", "Pectina"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "espinafre-cru", name: "Espinafre cru", category: "VITAMIN", iconKey: "leaf", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 23, protein100g: 2.9, carbs100g: 3.6, fat100g: 0.4, fiber100g: 2.2, sodium100gMg: 79, sugar100gG: 0.4, highlightMicros: ["Vitamina K", "Vitamina A", "Folato", "Ferro"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "cenoura-crua", name: "Cenoura crua", category: "VITAMIN", iconKey: "carrot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 41, protein100g: 0.9, carbs100g: 10, fat100g: 0.2, fiber100g: 2.8, sodium100gMg: 69, sugar100gG: 4.7, highlightMicros: ["Vitamina A (betacaroteno)"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "laranja", name: "Laranja", category: "VITAMIN", iconKey: "citrus", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 47, protein100g: 0.9, carbs100g: 12, fat100g: 0.1, fiber100g: 2.4, sodium100gMg: 0, sugar100gG: 9.4, highlightMicros: ["Vitamina C"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "pimentao-vermelho", name: "Pimentão vermelho", category: "VITAMIN", iconKey: "pepper", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 31, protein100g: 1, carbs100g: 6, fat100g: 0.3, fiber100g: 2.1, sodium100gMg: 4, sugar100gG: 4.2, highlightMicros: ["Vitamina C", "Vitamina A"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "sementes-abobora", name: "Sementes de abóbora", category: "MINERAL", iconKey: "circle-dot", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 559, protein100g: 30, carbs100g: 11, fat100g: 49, fiber100g: 6, sodium100gMg: 7, sugar100gG: 1.4, highlightMicros: ["Zinco", "Magnésio", "Ferro"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "amendoas", name: "Amêndoas", category: "MINERAL", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 579, protein100g: 21, carbs100g: 22, fat100g: 50, fiber100g: 12.5, sodium100gMg: 1, sugar100gG: 4.4, highlightMicros: ["Magnésio", "Vitamina E", "Cálcio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "melado-cana", name: "Melado de cana", category: "MINERAL", iconKey: "droplet", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 290, protein100g: 0, carbs100g: 75, fat100g: 0, fiber100g: 0, sodium100gMg: 37, sugar100gG: 60, highlightMicros: ["Ferro", "Cálcio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },

  { slug: "abacate", name: "Abacate", category: "GOOD_FAT", iconKey: "avocado", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 160, protein100g: 2, carbs100g: 8.5, fat100g: 14.7, fiber100g: 6.7, sodium100gMg: 7, sugar100gG: 0.7, highlightMicros: ["Gordura monoinsaturada", "Potássio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "azeite-oliva", name: "Azeite de oliva extra virgem", category: "GOOD_FAT", iconKey: "droplet", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 884, protein100g: 0, carbs100g: 0, fat100g: 100, fiber100g: 0, sodium100gMg: 2, sugar100gG: 0, highlightMicros: ["Gordura monoinsaturada", "Antioxidantes"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "castanha-para", name: "Castanha-do-pará", category: "GOOD_FAT", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 656, protein100g: 14, carbs100g: 12, fat100g: 66, fiber100g: 7.5, sodium100gMg: 3, sugar100gG: 2.3, highlightMicros: ["Selênio"], feasibilityTags: ["MEDIO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "nozes", name: "Nozes", category: "GOOD_FAT", iconKey: "nut", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 654, protein100g: 15, carbs100g: 14, fat100g: 65, fiber100g: 6.7, sodium100gMg: 2, sugar100gG: 2.6, highlightMicros: ["Ômega-3 (ALA)"], feasibilityTags: ["ALTO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "pasta-amendoim", name: "Pasta de amendoim integral", category: "GOOD_FAT", iconKey: "jar", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 588, protein100g: 25, carbs100g: 20, fat100g: 50, fiber100g: 6, sodium100gMg: 17, sugar100gG: 4, highlightMicros: ["Niacina"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
  { slug: "sementes-girassol", name: "Sementes de girassol", category: "GOOD_FAT", iconKey: "flower", containsAnimalProduct: false, isMeat: false, isFish: false, isDairy: false, isEgg: false, kcal100g: 584, protein100g: 21, carbs100g: 20, fat100g: 51, fiber100g: 8.6, sodium100gMg: 9, sugar100gG: 2.6, highlightMicros: ["Vitamina E", "Selênio"], feasibilityTags: ["BAIXO_CUSTO", "FACIL_DE_ACHAR"] },
];
